[package]
name = "assembler"
version = "0.1.0"
edition = "2021"
description = "An assembler for a fictive RISC-V based CPU"
repository = "https://git.mafiasi.de/Prj-MR/Assembler"
license = "MPL-2.0"
authors = ["Steven Becker <steven.becker@studium.uni-hamburg.de>"]
publish = ["mafiasi-gitea"]

[features]
default = ["mem_load_nop"]
full_nop = ["raw_nop", "mem_load_nop"]
raw_nop = []
mem_load_nop = []

[badges]
maintenance = { status = "experimental" }

[dependencies]
nom = "7.1.3"
clap = { version = "4.4.8", features = ["cargo"]}

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
assert_fs = "1.1.0"

[package.metadata.release]
sign-commit = true
sign-tag = true
registry = "mafiasi-gitea"
tag-name = "{{prefix}}{{version}}"
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://git.mafiasi.de/Prj-MR/Assembler/compare/{{tag_name}}...HEAD", exactly=1},
]
target = "x86_64-unknown-linux-gnu"