version: '3'

vars:
  TARGETS: 'x86_64-unknown-linux-gnu x86_64-pc-windows-gnu aarch64-apple-darwin'

tasks:
  build-releases:
    aliases: [br]
    cmds:
      - for: { var: TARGETS, split: ' ' }
        task: build-release
        vars:
          TARGET: '{{.ITEM}}'
      - for: { var: TARGETS, split: ' ' }
        task: rename-move-release
        vars:
          TARGET: '{{.ITEM}}'
      - task: sign-releases

  build-release:
    cmds:
      - cross build -r --target {{.TARGET}}
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/{{.TARGET}}/release/assembler'{{if eq .TARGET "x86_64-pc-windows-gnu"}}.exe{{end}}'
    requires:
      vars: [TARGET]

  rename-move-release:
    internal: true
    cmds:
      - cp target/{{.TARGET}}/release/assembler'{{if eq .TARGET "x86_64-pc-windows-gnu"}}.exe{{end}}' target/assembler-{{.TARGET}}'{{if eq .TARGET "x86_64-pc-windows-gnu"}}.exe{{end}}'
    sources:
      - target/{{.TARGET}}/release/assembler'{{if eq .TARGET "x86_64-pc-windows-gnu"}}.exe{{end}}'
    generates:
      - target/assembler-{{.TARGET}}'{{if eq .TARGET "x86_64-pc-windows-gnu"}}.exe{{end}}'
    requires:
      vars: [TARGET]

  sign-releases:
    cmds:
      - minisign -Sm target/assembler-* -t 'Assembler {{.VERSION}} - Steven Becker <steven.becker@studium.uni-hamburg.de>'
    sources:
      - target/assembler-*
    generates:
      - target/assembler-*.minisig
    vars:
      VERSION:
        sh: grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml | head -1
